[package]
name = "autogit"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
async-trait = "0.1.67"
http-body = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.29"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
validator = { version = "0.14.0", features = ["derive"] }